"use client";

/**
 * SkillAiAssistPanel — collapsible panel for the Workspace's Files tab.
 *
 * Wraps `useSkillAiAssist` with two surfaces:
 *   - Generate: a single textarea ("Describe the skill you want") + Generate
 *     button. Sends a `type: "generate"` SSE request.
 *   - Enhance: a checkbox grid of presets + a custom-instruction textarea +
 *     a Run button. Sends a `type: "enhance"` SSE request with the current
 *     SKILL.md as `current_content`.
 *
 * The panel is fully self-contained (toasts via `useToast`, no callbacks
 * except `onApply` which writes back to the form via the consumer's
 * `setSkillContentAndSyncTools`-style setter). A debug accordion shows the
 * SSE log when expanded — useful for debugging dynamic-agents wiring.
 */

import {
Bug,
Loader2,
Sparkles,
Square,
WandSparkles,
} from "lucide-react";
import React,{ useCallback,useMemo,useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from "@/components/ui/toast";
import { cn } from "@/lib/utils";

import {
ENHANCE_PRESETS,
useSkillAiAssist,
} from "@/components/skills/workspace/use-skill-ai-assist";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface SkillAiAssistPanelProps {
  /** Read the current SKILL.md content from the form. */
  getCurrentContent: () => string;
  /** Apply the AI result to the form. Receives parsed frontmatter when present. */
  onApply: (
    nextContent: string,
    parsed:
      | { name?: string; title?: string; description?: string }
      | null,
  ) => void;

  /** Optional name hint for context (sent with each request). */
  getNameHint?: () => string | undefined;
  /** Optional description hint for context. */
  getDescriptionHint?: () => string | undefined;

  /** Initial mode. Default: "generate". */
  defaultMode?: "generate" | "enhance";

  className?: string;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function SkillAiAssistPanel({
  getCurrentContent,
  onApply,
  getNameHint,
  getDescriptionHint,
  defaultMode = "generate",
  className,
}: SkillAiAssistPanelProps) {
  const { toast } = useToast();
  const [mode, setMode] = useState<"generate" | "enhance">(defaultMode);
  const [generateInput, setGenerateInput] = useState("");
  const [enhanceInput, setEnhanceInput] = useState("");
  const [presetSelected, setPresetSelected] = useState<Record<string, boolean>>(
    () => Object.fromEntries(ENHANCE_PRESETS.map((p) => [p.label, false])),
  );
  const [showDebug, setShowDebug] = useState(false);

  const ai = useSkillAiAssist({
    getCurrentContent,
    getNameHint,
    getDescriptionHint,
    onApply: (next, parsed) => {
      onApply(next, parsed);
      toast(
        mode === "generate" ? "Skill generated by AI" : "Skill enhanced by AI",
        "success",
      );
      // Clear inputs on successful apply (matches Builder behaviour).
      if (mode === "generate") setGenerateInput("");
      else {
        setEnhanceInput("");
        setPresetSelected(
          Object.fromEntries(ENHANCE_PRESETS.map((p) => [p.label, false])),
        );
      }
    },
  });

  // Surface non-abort errors as toasts.
  const lastErrorRef = React.useRef<Error | null>(null);
  React.useEffect(() => {
    if (ai.error && ai.error !== lastErrorRef.current) {
      lastErrorRef.current = ai.error;
      toast(ai.error.message, "error", 5000);
    }
    if (!ai.error) lastErrorRef.current = null;
  }, [ai.error, toast]);

  // Surface cancellations.
  const lastCancelledRef = React.useRef(false);
  React.useEffect(() => {
    if (ai.cancelled && !lastCancelledRef.current) {
      lastCancelledRef.current = true;
      toast("AI operation cancelled", "info");
    }
    if (!ai.cancelled) lastCancelledRef.current = false;
  }, [ai.cancelled, toast]);

  const togglePreset = useCallback((label: string) => {
    setPresetSelected((prev) => ({ ...prev, [label]: !prev[label] }));
  }, []);

  const onRunGenerate = useCallback(() => {
    void ai.generate(generateInput);
  }, [ai, generateInput]);

  const onRunEnhance = useCallback(() => {
    const presets = Object.entries(presetSelected)
      .filter(([, on]) => on)
      .map(([label]) => label);
    void ai.enhance({
      presetLabels: presets,
      customInstruction: enhanceInput,
    });
  }, [ai, enhanceInput, presetSelected]);

  const isBusy = ai.isBusy;

  const enhanceCanRun = useMemo(() => {
    if (isBusy) return false;
    if (enhanceInput.trim()) return true;
    return Object.values(presetSelected).some(Boolean);
  }, [isBusy, enhanceInput, presetSelected]);

  return (
    <div
      className={cn(
        "rounded-lg border border-border/60 bg-muted/30 overflow-hidden",
        className,
      )}
      data-testid="skill-ai-assist-panel"
    >
      {/* Header / mode toggle */}
      <div className="flex items-center justify-between gap-2 border-b border-border/50 bg-background/60 px-3 py-2">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <span className="text-sm font-semibold">AI Assist</span>
          {isBusy && (
            <Badge variant="secondary" className="text-xs">
              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
              {ai.status === "generating" ? "Generating…" : "Enhancing…"}
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-1">
          <div className="flex rounded-md border border-border/50 p-0.5 text-xs">
            <button
              type="button"
              onClick={() => setMode("generate")}
              className={cn(
                "px-2 py-0.5 rounded-sm transition-colors",
                mode === "generate"
                  ? "bg-background shadow-sm font-medium"
                  : "text-muted-foreground hover:text-foreground",
              )}
              aria-pressed={mode === "generate"}
            >
              Generate
            </button>
            <button
              type="button"
              onClick={() => setMode("enhance")}
              className={cn(
                "px-2 py-0.5 rounded-sm transition-colors",
                mode === "enhance"
                  ? "bg-background shadow-sm font-medium"
                  : "text-muted-foreground hover:text-foreground",
              )}
              aria-pressed={mode === "enhance"}
            >
              Enhance
            </button>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="p-3 space-y-3">
        {mode === "generate" && (
          <div className="space-y-2">
            <label
              htmlFor="ai-generate-input"
              className="text-xs font-medium text-muted-foreground"
            >
              Describe the skill you want to generate
            </label>
            <textarea
              id="ai-generate-input"
              className="w-full rounded-md border border-border/60 bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"
              rows={3}
              value={generateInput}
              onChange={(e) => setGenerateInput(e.target.value)}
              placeholder="e.g. A skill for triaging GitHub issues by labelling severity and routing to the right team."
              disabled={isBusy}
            />
            <div className="flex items-center justify-end gap-2">
              {isBusy ? (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={ai.cancel}
                >
                  <Square className="h-3.5 w-3.5 mr-1" />
                  Stop
                </Button>
              ) : (
                <Button
                  type="button"
                  size="sm"
                  onClick={onRunGenerate}
                  disabled={!generateInput.trim()}
                >
                  <WandSparkles className="h-3.5 w-3.5 mr-1" />
                  Generate
                </Button>
              )}
            </div>
          </div>
        )}

        {mode === "enhance" && (
          <div className="space-y-3">
            <div>
              <div className="text-xs font-medium text-muted-foreground mb-1.5">
                Quick presets
              </div>
              <div className="grid grid-cols-2 gap-1.5 sm:grid-cols-3">
                {ENHANCE_PRESETS.map((preset) => {
                  const on = !!presetSelected[preset.label];
                  return (
                    <label
                      key={preset.label}
                      className={cn(
                        "flex items-center gap-2 rounded-md border px-2 py-1.5 text-xs cursor-pointer transition-colors",
                        on
                          ? "border-primary/50 bg-primary/10"
                          : "border-border/60 hover:bg-muted/50",
                      )}
                    >
                      <input
                        type="checkbox"
                        checked={on}
                        onChange={() => togglePreset(preset.label)}
                        disabled={isBusy}
                        className="accent-primary"
                      />
                      <span>{preset.label}</span>
                    </label>
                  );
                })}
              </div>
            </div>
            <div>
              <label
                htmlFor="ai-enhance-input"
                className="text-xs font-medium text-muted-foreground"
              >
                Custom instructions (optional)
              </label>
              <textarea
                id="ai-enhance-input"
                className="mt-1 w-full rounded-md border border-border/60 bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"
                rows={2}
                value={enhanceInput}
                onChange={(e) => setEnhanceInput(e.target.value)}
                placeholder="e.g. Add a step to verify environment variables before running."
                disabled={isBusy}
              />
            </div>
            <div className="flex items-center justify-end gap-2">
              {isBusy ? (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={ai.cancel}
                >
                  <Square className="h-3.5 w-3.5 mr-1" />
                  Stop
                </Button>
              ) : (
                <Button
                  type="button"
                  size="sm"
                  onClick={onRunEnhance}
                  disabled={!enhanceCanRun}
                >
                  <WandSparkles className="h-3.5 w-3.5 mr-1" />
                  Enhance
                </Button>
              )}
            </div>
          </div>
        )}

        {/* Debug accordion */}
        {(ai.debugLog.length > 0 || ai.promptSent) && (
          <div className="border-t border-border/50 pt-2">
            <button
              type="button"
              onClick={() => setShowDebug((v) => !v)}
              className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"
              aria-expanded={showDebug}
              aria-controls="ai-debug-content"
            >
              <Bug className="h-3 w-3" />
              {showDebug ? "Hide" : "Show"} debug log ({ai.debugLog.length})
            </button>
            {showDebug && (
              <div
                id="ai-debug-content"
                className="mt-2 space-y-2 text-xs"
                data-testid="ai-debug-content"
              >
                {ai.promptSent && (
                  <div className="rounded-md border border-border/50 bg-background p-2 font-mono whitespace-pre-wrap break-words">
                    <div className="text-muted-foreground mb-1">Prompt</div>
                    {ai.promptSent}
                  </div>
                )}
                <ScrollArea className="max-h-40 rounded-md border border-border/50 bg-background p-2 font-mono">
                  {ai.debugLog.map((line, i) => (
                    <div key={i} className="text-muted-foreground">
                      {line}
                    </div>
                  ))}
                </ScrollArea>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
