// AUTO-GENERATED by scripts/extract-rbac-resources.py — do not edit
// Spec 102: docs/docs/specs/102-comprehensive-rbac-tests-and-completion/data-model.md §E4
//
// Catalog of (resource, scope) pairs referenced by either runtime (TS or Py).
// Used by scripts/validate-realm-config.py to assert realm-config.json completeness.
//
// To regenerate: `python3 scripts/extract-rbac-resources.py`

export const KEYCLOAK_RESOURCE_CATALOG = {
  admin_ui: { scopes: ["admin", "view"] as const },
} as const;

export type KeycloakResourceName = keyof typeof KEYCLOAK_RESOURCE_CATALOG;
